config/routes.rb
Rails.application.routes.draw do
  resources :consults
  resources :patients
  resources :doctors
  resources :specialities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "doctors#index"
end

app/models/speciality.rb
class Speciality < ApplicationRecord
  has_many :doctors
end

app/controllers/specialities_controller.rb
class SpecialitiesController < ApplicationController
  before_action :set_speciality, only: %i[ show edit update destroy ]

  # GET /specialities or /specialities.json
  def index
    @specialities = Speciality.all
  end

  # GET /specialities/1 or /specialities/1.json
  def show
  end

  # GET /specialities/new
  def new
    @speciality = Speciality.new
  end

  # GET /specialities/1/edit
  def edit
  end

  # POST /specialities or /specialities.json
  def create
    @speciality = Speciality.new(speciality_params)

    respond_to do |format|
      if @speciality.save
        format.html { redirect_to @speciality, notice: "Speciality was successfully created." }
        format.json { render :show, status: :created, location: @speciality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specialities/1 or /specialities/1.json
  def update
    respond_to do |format|
      if @speciality.update(speciality_params)
        format.html { redirect_to @speciality, notice: "Speciality was successfully updated." }
        format.json { render :show, status: :ok, location: @speciality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @speciality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specialities/1 or /specialities/1.json
  def destroy
    @speciality.destroy
    respond_to do |format|
      format.html { redirect_to specialities_url, notice: "Speciality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speciality
      @speciality = Speciality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def speciality_params
      params.require(:speciality).permit(:name)
    end
end

app/helpers/specialities_helper.rb
module SpecialitiesHelper
end

app/views/specialities/_form.html.erb
<%= form_with(model: speciality) do |form| %>
  <% if speciality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(speciality.errors.count, "error") %> prohibited this speciality from being saved:</h2>

      <ul>
        <% speciality.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/specialities/edit.html.erb
<h1>Editing Speciality</h1>

<%= render 'form', speciality: @speciality %>

<%= link_to 'Show', @speciality %> |
<%= link_to 'Back', specialities_path %>

app/views/specialities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Specialities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Doctors</th>
      <th>Consults</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @specialities.each do |speciality| %>
      <tr>
        <td><%= speciality.name %></td>
        <td><%= link_to speciality.doctors.count, doctors_path(:speciality_id => speciality.id) %></td>
        <td>
          <% total = 0 %>
          <% speciality.doctors.each do |p| %>
            <% total = total + p.consults.count %>
          <% end %>
          <%= link_to total, consults_path(:speciality_id => speciality.id) %>
        </td>
        <td><%= link_to 'Show', speciality %></td>
        <td><%= link_to 'Edit', edit_speciality_path(speciality) %></td>
        <td><%= link_to 'Destroy', speciality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speciality', new_speciality_path %>

app/views/specialities/new.html.erb
<h1>New Speciality</h1>

<%= render 'form', speciality: @speciality %>

<%= link_to 'Back', specialities_path %>

app/views/specialities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speciality.name %>
</p>

<%= link_to 'Edit', edit_speciality_path(@speciality) %> |
<%= link_to 'Back', specialities_path %>