config/routes.rb
Rails.application.routes.draw do
  resources :consults
  resources :patients
  resources :doctors
  resources :specialities
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "doctors#index"
end

app/models/consult.rb
class Consult < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/controllers/consults_controller.rb
class ConsultsController < ApplicationController
  before_action :set_consult, only: %i[ show edit update destroy ]

  # GET /consults or /consults.json
  def index
    @consults = Consult.all
    @consults = Consult.joins(:doctor).where(:doctor => {:speciality_id => params[:speciality_id]}) if params[:speciality_id]
    @consults = @consults.where(:doctor_id => params[:doctor_id]) if params[:doctor_id]
    @consults = Consult.joins(:doctor).joins(:patient).where("doctors.first_name LIKE :filter OR doctors.last_name LIKE :filter OR patients.first_name LIKE :filter OR patients.last_name LIKE :filter", :filter => params[:filter])
  end

  # GET /consults/1 or /consults/1.json
  def show
  end

  # GET /consults/new
  def new
    @consult = Consult.new
  end

  # GET /consults/1/edit
  def edit
  end

  # POST /consults or /consults.json
  def create
    @consult = Consult.new(consult_params)

    respond_to do |format|
      if @consult.save
        format.html { redirect_to @consult, notice: "Consult was successfully created." }
        format.json { render :show, status: :created, location: @consult }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consults/1 or /consults/1.json
  def update
    respond_to do |format|
      if @consult.update(consult_params)
        format.html { redirect_to @consult, notice: "Consult was successfully updated." }
        format.json { render :show, status: :ok, location: @consult }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consult.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consults/1 or /consults/1.json
  def destroy
    @consult.destroy
    respond_to do |format|
      format.html { redirect_to consults_url, notice: "Consult was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consult
      @consult = Consult.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consult_params
      params.require(:consult).permit(:date, :doctor_id, :patient_id)
    end
end

app/helpers/consults_helper.rb
module ConsultsHelper
end

app/views/consults/_form.html.erb
<%= form_with(model: consult) do |form| %>
  <% if consult.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consult.errors.count, "error") %> prohibited this consult from being saved:</h2>

      <ul>
        <% consult.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.collection_select(:doctor_id, Doctor.all, :id, :full_name) %>
  </div>

  <div class="field">
    <%= form.label :patient_id %>
    <%= form.collection_select(:patient_id, Patient.all, :id, :last_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consults/edit.html.erb
<h1>Editing Consult</h1>

<%= render 'form', consult: @consult %>

<%= link_to 'Show', @consult %> |
<%= link_to 'Back', consults_path %>

app/views/consults/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consults</h1>
<form action="/consults" method="get">
  <input type="text" name="filter" value=""/>
  <input type="submit"/>
</form>
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Doctor</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consults.each do |consult| %>
      <tr>
        <td><%= consult.date %></td>
        <td><%= consult.doctor.full_name %></td>
        <td><%= consult.patient.full_name %></td>
        <td><%= link_to 'Show', consult %></td>
        <td><%= link_to 'Edit', edit_consult_path(consult) %></td>
        <td><%= link_to 'Destroy', consult, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consult', new_consult_path %>

app/views/consults/new.html.erb
<h1>New Consult</h1>

<%= render 'form', consult: @consult %>

<%= link_to 'Back', consults_path %>

app/views/consults/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @consult.date %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @consult.doctor_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @consult.patient_id %>
</p>

<%= link_to 'Edit', edit_consult_path(@consult) %> |
<%= link_to 'Back', consults_path %>